- name: Deploy to VM
  run: |
    ssh -o StrictHostKeyChecking=no root123@20.205.19.38 << 'EOF'

      # Clone repo if not exists
      if [ ! -d "/home/root123/20262904" ]; then
        git clone https://github.com/ijazahmed786/20262904.git /home/root123/20262904
      fi

      cd /home/root123/20262904
      git pull origin main

      echo "Copying files to /var/www/html"

      sudo cp -r * /var/www/html/

      echo "Deployment completed"

    EOF
