name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AZURE_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to VM
        run: |
          ssh -o StrictHostKeyChecking=no root123@20.205.19.38 << 'EOF'
            if [ ! -d "/home/root123/20262904" ]; then
              git clone https://github.com/ijazahmed786/20262904.git /home/root123/20262904
            fi

            cd /home/root123/20262904
            git pull origin main

            echo "Deployment completed"
          EOF
